add_newline = true
command_timeout = 900

format = """
[╭─](bold bright-black)$username$directory$git_branch$git_status$python
[╰─](bold bright-black)$character"""

[username]
show_always = true
style_user = "bold 147"
format = "[$user]($style) "

[directory]
style = "bold 39"
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
symbol = " "
style = "bold 177"
format = "[($symbol$branch)]($style) "

[git_status]
style = "bold 203"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = "py "
style = "bold 111"
format = "[${symbol}${virtualenv}]($style) "

[character]
success_symbol = "[❯](bold 78)"
error_symbol = "[❯](bold 203)"
